tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "bash"
brew "bat"
brew "dust"
brew "exa"
brew "exiftool"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "go"
brew "graphviz"
brew "grep"
brew "hyperfine"
brew "jq"
brew "mas"
brew "neovim"
brew "nmap"
brew "openssl"
brew "procs"
brew "ripgrep"
brew "rmlint"
brew "rustup-init"
brew "s-search"
brew "semgrep"
brew "shellcheck"
brew "shfmt"
brew "tealdeer"
brew "terraform-docs"
brew "tfenv"
brew "tflint"
brew "tfsec"
brew "tokei"
brew "watch"
brew "xh"
brew "youtube-dl"
brew "zenith"
brew "zsh"
cask "1password-cli"
cask "1password"
cask "adguard"
cask "appcleaner"
cask "discord"
cask "docker"
cask "dropbox"
cask "imageoptim"
cask "iterm2"
cask "pdf-squeezer"
cask "raycast"
cask "rectangle"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "AdGuard for Safari", id: 1440147259
mas "Dark Reader for Safari", id: 1438243180
mas "SmileAllDay", id: 1180442868
mas "The Unarchiver", id: 425424353
mas "Vinegar - Tube Cleaner", id: 1591303229
